// <auto-generated />
namespace GigHub1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class userAddDateBirth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userAddDateBirth));
        
        string IMigrationMetadata.Id
        {
            get { return "201810070922047_userAddDateBirth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
